# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: requirements-txt-fixer
        files: requirements.*.in

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: Format Python
        language_version: python3.10

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Format Python imports
        args:
          - --profile=black

  - repo: https://github.com/jazzband/pip-tools
    rev: 6.9.0
    hooks:
      - id: pip-compile
        name: Compile site requirements
        files: requirements.(in|txt)

      - id: pip-compile
        name: Compile automation requirements
        files: requirements.*.(in|txt)
        args:
          - requirements-automate.in
          - --output-file=requirements-automate.txt

      - id: pip-compile
        alias: pip-compile-upgrade
        name: Upgrade site dependencies
        files: requirements.(in|txt)
        stages: [manual]
        args:
          - --upgrade

      - id: pip-compile
        alias: pip-compile-upgrade
        name: Upgrade automation dependencies
        files: requirements.*.(in|txt)
        stages: [manual]
        args:
          - requirements-automate.in
          - --upgrade
          - --output-file=requirements-automate.txt

  - repo: https://github.com/Riverside-Healthcare/djlint
    rev: v1.19.3
    hooks:
      - id: djlint-jinja
        name: Autoformat jinja files
        types_or: [html]
        args:
          - --reformat
