name: Build Episode

on:
  repository_dispatch:
    types: [publish]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-automate.txt
      - name: build page from issue
        env:
          issue_number: ${{ github.event.client_payload.issue_number }}
        run: python publish/add_episode_from_issue.py $issue_number
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT_TOKEN}}
          commit-message: Create ${{ github.event.client_payload.issue_number }}
          title: Create ${{ github.event.client_payload.issue_number }}
          body: Creates ${{ github.event.client_payload.issue_number }}
          branch: bot-creates-topic-publish-${{ github.event.client_payload.issue_number }}
          delete-branch: true
          labels: publish
